### ISSUE TITLE
unable to recognize "database/deployment/database-deployment.yaml"

### ISSUE THREAD

**Issue by GoestaO** [katarzyna-dusza/k8s-medium#1]
I get the following error:
```
/k8s-medium kubectl apply -f database/deployment/database-deployment.yaml
error: unable to recognize "database/deployment/database-deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```
is `apiVersion: apps/v1` the correct one?

**Comment by bagminer** [comment]
Yeah, you have to change the `apiVersion: extensions/v1beta1` to `apiVersion: apps/v1`. Deployment lies in apps API group in 1.16 version

**Comment by katarzyna-dusza** [comment]
Hey!

Thank you, @GoestaO for opening this issue and you, @bagminer, for your contribution and putting more context about Kubernetes updates! ✋You are both right. I will fix it ASAP, so other people won't have this problem in the future.
