### ISSUE TITLE
Should you be exposing the Database service with an external IP?

### ISSUE THREAD

**Issue by ZkHaider** [katarzyna-dusza/k8s-medium#4]
Im coming from the mobile world (iOS / Android) so forgive me if these questions seem a little newbie.

<img width="535" alt="image" src="https://user-images.githubusercontent.com/7844550/74694092-92a49480-51a3-11ea-880e-0a73e6279c0b.png">

I noticed that the Mongo service has an external IP attached to it after following this tutorial. Isn't this dangerous and shouldn't you safeguard your DB from external access?

**Comment by katarzyna-dusza** [comment]
Hey @ZkHaider, thanks for opening this issue! :) 

Actually yes, you are right 👍
I believe I was testing something and left it afterward. I will create a PR with a short fix to avoid future confusion.
